### ISSUE TITLE
Error registering MBean[Ebean:server=RealisticChat2] caudron 1.7.10 forge 1240  realisticchat_1.0.1

### ISSUE THREAD

**Issue by BrotherLavarius** [redinzane/RealisticChat#1]
{code}
[13:02:22] [Server thread/ERROR]: Error registering MBean[Ebean:server=RealisticChat2]
java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372) ~[?:1.7.0_72]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:585) ~[?:1.7.0_72]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848) ~[?:1.7.0_72]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322) ~[?:1.7.0_72]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[?:1.7.0_72]
        at com.avaje.ebeaninternal.server.core.DefaultServer.registerMBeans(DefaultServer.java:389) [DefaultServer.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:226) [DefaultServerFactory.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:64) [DefaultServerFactory.class:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) [EbeanServerFactory.class:?]
        at org.bukkit.plugin.java.JavaPlugin.init(JavaPlugin.java:362) [JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:509) [PluginClassLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) [JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at io.github.redinzane.realisticchat.RealisticChat.<init>(RealisticChat.java:17) [realisticchat_1.0.1.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.7.0_72]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [?:1.7.0_72]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.7.0_72]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [?:1.7.0_72]
        at java.lang.Class.newInstance(Class.java:379) [?:1.7.0_72]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) [PluginClassLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458) [ayq.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:350) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
{code}

**Comment by redstales** [comment]
Any more information? Does this happen on startup or during running, is it reproducable?

**Comment by trichner** [comment]
What database are you using? The default sqlite? This looks like a JPA problem.

**Comment by BrotherLavarius** [comment]
---Any more information? Does this happen on startup or during running, is it reproducable?
On start up, yes every launch .
Please provide what additional info needed? I can provide anything if you say what you need.
Host: linux 64,java 1.7.0_72 build. I will testout the plugin at night for me(UTC+4) 
--What database are you using? The default sqlite? This looks like a JPA problem.
Didn't even change the config. Null install.

**Comment by trichner** [comment]
The database is set in the bukkit.yml, so you have the default there?

**Comment by BrotherLavarius** [comment]
--The database is set in the bukkit.yml, so you have the default there?

---

database:
  username: bukkit
  isolation: SERIALIZABLE
  driver: org.sqlite.JDBC
  password: walrus
  url: jdbc:sqlite:{DIR}{NAME}.db

---

 yes the default one

**Comment by trichner** [comment]
looks good

**Comment by trichner** [comment]
It looks like you have the java SecurityManager enabled and some policy that doesn't like Beans. Can you try to disable the SecurityManager?

Edit: e.g. if you have `-Djava.security.policy` in your jvm options

**Comment by BrotherLavarius** [comment]
Done both the picture is the same

---

[17:23:33] [Server thread/ERROR]: Error registering MBean[Ebean:server=RealisticChat2]
java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372) ~[?:1.7.0_72]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:585) ~[?:1.7.0_72]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848) ~
[?:1.7.0_72]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322) ~[?:1.7.0_72]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[?:1.7.0_72]
        at com.avaje.ebeaninternal.server.core.DefaultServer.registerMBeans(DefaultServer.java:389) [DefaultServer.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:226) [DefaultServerFactory
.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:64) [DefaultServerFactory.
class:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) [EbeanServerFactory.class:?]
        at org.bukkit.plugin.java.JavaPlugin.init(JavaPlugin.java:362) [JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:509) [PluginClassLoader.class:git-Cauldron-MCPC
-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) [JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212
]
        at io.github.redinzane.realisticchat.RealisticChat.<init>(RealisticChat.java:17) [realisticchat_1.0.1.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.7.0_72]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [?:1.7.0_72]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.7.0_72]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [?:1.7.0_72]
        at java.lang.Class.newInstance(Class.java:379) [?:1.7.0_72]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) [PluginClassLoader.class:git-Cauldron-MCPC-Plu
s-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458) [ayq.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:350) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]

---

**Comment by trichner** [comment]
Some policy here seems wrong. What OS are you using? What Java variant? What policy files do you have?

Edit: Do you have an ebeans.properties file?

**Comment by BrotherLavarius** [comment]
Linux mshade01.local 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)

no spechial policy installed,just forgot actually to trow it from atributes,both the result the same.

did not find anything looking like ebeans.properties

**Comment by redstales** [comment]
https://community.oracle.com/thread/1540187?start=0&tstart=0 Can you try the method outlined at the bottom of this forum thread?

**Comment by BrotherLavarius** [comment]
Done, not reproducing, i will get some one to test it shortly.
Please add a fix or list the workaround in the faq section.

**Comment by BrotherLavarius** [comment]
Status update this thing crashes the sever to OOM at PermGen. I will try to update it to 8java and launch the server there. Both fnow after launcher with 3gb free  xms4096\xmx4096 mode it OOM's after 2 phrases in chat.

**Comment by BrotherLavarius** [comment]
Status update: well launching on java 8 make things better thiss lad to apply https://community.oracle.com/thread/1540187?start=0&tstart=0

**Comment by redstales** [comment]
I don't quite get what you're trying to say in the last 2 comments.

**Comment by redstales** [comment]
No followup.
